### ISSUE TITLE
Think about switching to Node.js

### ISSUE THREAD

**Issue by goonyaa** [goonyaa/lsb#1]
Checkout node modules like https://github.com/SBoudrias/Inquirer.js and https://github.com/tj/commander.js

What do you guys think @Tarlord @DeWenS ?

**Comment by DeWenS** [comment]
First one looks pretty good, but switching is up to you

**Comment by goonyaa** [comment]
@DeWenS 
Ok. BTW it was @Tarlord idea in some sense, and I'm also fine with switching.
Then decided.
